/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'ttruong' at '1/14/15 4:05 PM' with Gradle 2.2.1
 *
 * @author ttruong, @date 1/14/15 4:05 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
