/*
 * This Scala Testsuite was auto generated by running 'gradle init --type scala-library'
 * by 'ttruong' at '1/14/15 4:05 PM' with Gradle 2.2.1
 *
 * @author ttruong, @date 1/14/15 4:05 PM
 */

import org.scalatest.FunSuite
import org.junit.runner.RunWith
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("someLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
